<template>
  <div
    class="flex items-center justify-center flex-wrap gap-5 max-h-[30rem] overflow-y-scroll"
  >
    <template v-if="allActiveTokens?.length">
      <ActiveTokenCard
        v-for="activeToken in allActiveTokens"
        :key="activeToken.token"
        :token="activeToken.token"
        :used-by="activeToken.usedBy"
        :issued-at="activeToken.issuedAt"
      />
    </template>

    <Inconvenience
      v-else
      img-src="/images/data_reports.svg"
      img-style="max-w-[12rem] md:max-w-[17rem]"
      class="mt-6"
    >
      You haven't generated any active tokens yet.
      <br />
      Active tokens generated by you show up here.
    </Inconvenience>
  </div>
</template>

<script setup>
const { allActiveTokens, getGeneratedTokens } = useActiveToken();
getGeneratedTokens();
</script>
